FROM arm32v7/ubuntu:trusty

RUN apt-get update && \
    apt-get -yq install cron php5 php5-curl git-core

RUN cd /var/www/html && rm index.html && \
    git clone https://github.com/redref/Cheky.git . && \
    chmod -R 755 * && \
    chown -R www-data:www-data * 

RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf && \
        sed -i "s/variables_order.*/variables_order = \"EGPCS\"/g" /etc/php5/apache2/php.ini

#RUN echo "* * * * * root /usr/bin/php /var/www/html/check.php" > /etc/cron.d/lbc
RUN echo "* 0/48 * * * root /usr/bin/php /var/www/html/check.php" > /etc/cron.d/lbc

EXPOSE 80
CMD cron && apache2ctl -k graceful -D FOREGROUND
